In [1]:
import pickle
import numpy as np
import fun_dual as f
from itertools import product,permutations

# Print solution Y^(a,k), C, Q

In [2]:
n,K,d=8,9,3

with open("inf_cert_8", 'rb') as inf_cert:
    Y,C=pickle.load(inf_cert)
    Q=np.zeros(n+1)

y=f.yijtp_fun(Y,n)

f4,_=f.f4_fun(n)

f2M,_=f.f2M_fun(n)

D=f.D_fun(C,n,d)

for a in range(n+1):
    for k in range(a,int((n+a)/2)+1):
        
        print("Y^(%s,%s)=%s\n" % (a,k,Y[f2M[a,k]]))
        
print("C=%s\n" % (C))
print("D=%s\n" % (D))
print("Q=%s\n" % (Q))

Y^(0,0)=[[ 203.  -65.  -54.  104.   87.   40. -208. -245.  567.]
 [ -65.  103.    4.  -43.  -41.    4.   63.   99.  -39.]
 [ -54.    4.   45.  -51.  -32.   -4.   58.   44. -265.]
 [ 104.  -43.  -51.   90.   53.    8. -109. -109.  364.]
 [  87.  -41.  -32.   53.   69.  -15.  -86. -121.  137.]
 [  40.    4.   -4.    8.  -15.   75.  -43.  -41.  198.]
 [-208.   63.   58. -109.  -86.  -43.  215.  244. -616.]
 [-245.   99.   44. -109. -121.  -41.  244.  342. -473.]
 [ 567.  -39. -265.  364.  137.  198. -616. -473. 2934.]]

Y^(0,1)=[[2984. -426. -163. -254.  356. 1048. 1524.]
 [-426.  732. -407.  -25.   76. -576. -888.]
 [-163. -407.  607.   46. -190.   91.  105.]
 [-254.  -25.   46.  174. -169. -239. -292.]
 [ 356.   76. -190. -169.  497.  282.  239.]
 [1048. -576.   91. -239.  282. 1406. 2364.]
 [1524. -888.  105. -292.  239. 2364. 5048.]]

Y^(0,2)=[[ 6808.  1459.   116.   -28. -1411.]
 [ 1459.  3525. -1235.  -878.  1003.]
 [  116. -1235.  1091.   380.  -285.]
 [  -28.  -878.   380.  1121. 

# Objective value

In [3]:
obj_val = (K*D[0]-C[0])+(2**n/K-1)*Q[0] - y[f4[0, 0, 0, 0]]

print("obj_val=%s" % obj_val)


obj_val=0.989453296541484


# Constraints

In [4]:
#### Structure constraints ####

const=[]

for i, j, t, p in f4.keys():

    if (t - p) % 2 == 0 and not i==0 and not j == 0 and not i == j == t == p:

        zero = sum([y[f4[a, b, c, q]] + Q[a+b-c-q]
                    for a, b, c, q in f4.keys() if t - p == c - q and (i, j, i + j - t - p) in 
                    list(permutations((a, b, a + b - c - q)))])

        const.append(abs(zero))


print("Structure constraints = %s" % max(const))

const=[]

for i in range(1, d):
    zero = K*D[i]-C[i] +(2**n/K-2)*Q[i]-Q[0] - y[f4[i, i, i, i]] - 2*y[f4[i, 0, 0, 0]]

    const.append(abs(zero))

print("Knill Lafllame 1 = %s" % max(const))

const=[]

for i in range(d, n+1):
    zero = K*D[i] +(2**n/K-2)*Q[i]-Q[0] - y[f4[i, i, i, i]] - 2*y[f4[i, 0, 0, 0]]
    const.append(abs(zero))
        
print("Knill Lafllame 2 = %s" % max(const))

Structure constraints = 8.526512829121202e-14
Knill Lafllame 1 = 4.263256414560601e-14
Knill Lafllame 2 = 1.4210854715202004e-14


# Minimal eigenvalue

In [5]:
ref = np.infty
for i in range(len(Y)):
    min_eig = min(np.linalg.eigvals(Y[i].astype('float')))
    if ref >= min_eig:
        ref = min_eig

print("Min eigenvalue = %s" % ref)

Min eigenvalue = 0.0010435795312035237
